import json

class Exporter:
    @staticmethod
    def to_markdown(title, content, mode):
        return f"# {title}\n\n**Mode:** {mode}\n\n---\n\n{content}\n\n---\n*Generated by Academic AI Automation Kit*"

    @staticmethod
    def to_json(title, content, mode):
        return json.dumps({
            "title": title,
            "mode": mode,
            "content": content,
            "tool": "Academic AI Automation Kit"
        }, indent=4)
